In [1]:
# Create a list of 1s in 15 times using plain python
ones_list = []
for i in range(15):
    ones_list.append(1)
print(ones_list)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [2]:
# List of 15 numbers of 7s
sevens_list = []
for i in range(15):
    sevens_list.append(7)
print(sevens_list) 


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [3]:
# List numbers from 100 to 150
numbers_list = []
for i in range(100, 151):
    numbers_list.append(i)
print(numbers_list)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [4]:
# List of even numbers between 0 and 100
even_numbers = []
for i in range(0, 101):
    if i % 2 == 0:
        even_numbers.append(i)
print(even_numbers)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [5]:
# List the years that are leap years between 1950 and 2020 devisible by 4
leap_years = []
for year in range(1950, 2021):
    if year % 4 == 0:
        leap_years.append(year) 
print(leap_years)

[1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


In [6]:
import numpy as np
# Array of 15 zeros
zeros_array = np.zeros(15).astype(int)
zeros_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Array of 15 ones
ones_array = np.ones(15).astype(int)
ones_array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
# Array of 15 numbers of 7s
seven_array = np.ones(15).astype(int) * 7
seven_array

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [9]:
# Array numbers from 100 to 150
numbers_array = np.arange(100, 151)
numbers_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [10]:
# Array numbers from 1900 to 2021
numbers_array = np.arange(1900, 2022)
numbers_array


array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [11]:
# Array of even numbers between 0 and 100
even_numbers_array = np.arange(0, 101, 2)
even_numbers_array

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [12]:
# array of leap years between 1950 and 2020 devisible by 4
leap_years_array = np.arange(1950, 2021, 4) 
leap_years_array

array([1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978, 1982, 1986, 1990,
       1994, 1998, 2002, 2006, 2010, 2014, 2018])

In [13]:
# It is easy to do with Numpy than plain python. We can generate the code in one line with Numpy but with plain python we need to write more lines of code to achieve the same result.

In [14]:
data = np.array([5,6,9,2,19,18,11,7])
# Find the position of the largest value
largest_value_position = np.argmax(data)
largest_value_position

np.int64(4)

In [15]:
# Matrix with values from 1 to 49 reshaped to 7 rows and 7 columns
matrix = np.arange(1, 50).reshape(7, 7)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [16]:
# Create the same matrix without NumPy
matrix_list = []
for i in range(1, 50):
    matrix_list.append(i)
# Reshape the list into a 7x7 matrix
matrix_7x7 = []
for i in range(0, len(matrix_list), 7):
    matrix_7x7.append(matrix_list[i:i+7])
matrix_7x7

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [17]:
# Generate 8 by 8 matrix with random values between 0 and 5
random_matrix = np.random.randint(0, 6, (8, 8))
random_matrix

array([[5, 2, 2, 1, 1, 3, 2, 0],
       [3, 4, 5, 3, 0, 4, 4, 3],
       [1, 4, 0, 5, 5, 4, 2, 5],
       [2, 4, 1, 5, 2, 2, 3, 2],
       [4, 4, 4, 2, 3, 1, 5, 4],
       [4, 2, 3, 3, 0, 1, 1, 2],
       [4, 0, 3, 3, 4, 4, 3, 3],
       [0, 1, 1, 5, 3, 3, 4, 0]], dtype=int32)

In [18]:
# Generate 8 by 8 matrix using standard normal distribution values between -3 and 3
normal_matrix = np.random.randn(8, 8)
normal_matrix


array([[-1.02915531,  1.91697299, -0.83802444,  1.70081203, -0.79840788,
        -0.13517396,  0.35234083, -0.35264708],
       [-0.18476518, -0.76251511,  0.97701424, -0.45373439,  0.35113199,
         0.026374  ,  0.44383327, -0.41751545],
       [ 0.69229943, -0.21883394,  1.1684039 , -0.17358471,  0.52244783,
         0.99281424,  0.44021927,  0.91673884],
       [ 1.72424816, -0.2618979 , -0.54765275, -0.47187042, -1.67411396,
         1.24717029,  0.56393915, -0.23198608],
       [ 0.23835101,  0.92066027, -0.81357506,  0.33245376, -0.43209975,
         0.95771878, -1.00344013, -0.87409501],
       [-0.93580874,  0.41323283,  0.74674688,  1.56401859, -0.32375025,
        -0.85546945,  0.79437154,  0.09983896],
       [ 0.34638775,  1.00500526, -0.40986031, -1.14314745,  1.73995799,
        -0.99202366,  0.69147682, -0.00318059],
       [-1.31523157,  0.72994602,  0.38210625,  0.02553049, -0.6077376 ,
         0.23371852,  0.14864769, -1.56179881]])

In [19]:
# Create linear space of 10 numbers between 0 and 1
linear_space = np.linspace(0, 1, 10)
linear_space

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
# Generate 10 by 10 matrix with linear space of numbers between 0 and 5
linear_space_matrix = np.linspace(0, 5, 100).reshape(10, 10)
linear_space_matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.6363636

In [21]:
# Create this same matrix without Numpy
start = 0
end = 5
num = 100
step = (end - start) / (num - 1)
values = []
for i in range(num):
    values.append(start + i * step)

# Reshape the list into a 10x10 matrix
matrix_10x10 = []
for i in range(0, len(values), 10):
    matrix_10x10.append(values[i:i+10])
matrix_10x10            


[[0.0,
  0.050505050505050504,
  0.10101010101010101,
  0.15151515151515152,
  0.20202020202020202,
  0.25252525252525254,
  0.30303030303030304,
  0.35353535353535354,
  0.40404040404040403,
  0.45454545454545453],
 [0.5050505050505051,
  0.5555555555555556,
  0.6060606060606061,
  0.6565656565656566,
  0.7070707070707071,
  0.7575757575757576,
  0.8080808080808081,
  0.8585858585858586,
  0.9090909090909091,
  0.9595959595959596],
 [1.0101010101010102,
  1.0606060606060606,
  1.1111111111111112,
  1.1616161616161615,
  1.2121212121212122,
  1.2626262626262625,
  1.3131313131313131,
  1.3636363636363635,
  1.4141414141414141,
  1.4646464646464645],
 [1.5151515151515151,
  1.5656565656565655,
  1.6161616161616161,
  1.6666666666666667,
  1.7171717171717171,
  1.7676767676767677,
  1.8181818181818181,
  1.8686868686868687,
  1.9191919191919191,
  1.9696969696969697],
 [2.0202020202020203,
  2.0707070707070705,
  2.121212121212121,
  2.1717171717171717,
  2.2222222222222223,
  2.27272727

In [22]:
# create a 3 by 5 matrix
matrix = np.array([[23, 34, 54, 31, 75],
    [33, 56, 78, 65, 97],
    [41, 32, 11, 39, 51]])
matrix

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [23]:
# Generate a 8 by 16 marix
values = np.arange(128,256).reshape(8, 16)
values

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [24]:
# Generate a 10 by 10 matrix using linear space of numbers between 0 and 5
linear_space_matrix = np.linspace(0.05, 5, 100).reshape(10, 10)
data = linear_space_matrix.round(2)
data

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

In [25]:
# create a dataset by 6 by 6 matrix with values from 1 to 36
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [26]:
# create a slice of the dataset

slice_dataset = dataset[3:6, 2:6]
slice_dataset

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [27]:
# pick out a column of the dataset
slice_data = dataset[0:4, 3]
slice_data

array([ 4, 10, 16, 22])

In [28]:
# pick out a row of the dataset
slice_data = dataset[2:3,:]
slice_data

array([[13, 14, 15, 16, 17, 18]])

In [29]:
# pickout the three rows
slice_data = dataset[3:6,:]
slice_data

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [30]:
# Broadcasting in Numpy
# create a dataset with the values from 1 to 50 reshaped to 7 by 7 matrix
dataset = np.arange(1, 50).reshape(7, 7)
dataset

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [31]:
# Add 50 to the all the values in the dataset
dataset = dataset + 50
dataset

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [32]:
# Get sum of all the values in the dataset
total = np.sum(dataset)
total

np.int64(3675)

In [33]:
# Get sum only the odd values in the dataset
boolean_values = dataset % 2 != 0
odd_values = dataset[boolean_values]
odd_values_sum = np.sum(odd_values)
odd_values_sum

# Step 2 -comprehensive for the avove code
# odd_values_sum = np.sum(dataset[dataset % 2 != 0])  
# odd_values_sum

np.int64(1875)

In [34]:
# get the standard deviation of the dataset
standard_deviation = np.std(dataset)
standard_deviation

np.float64(14.142135623730951)

In [35]:
# Get the sum of the rows in the dataset
row_sums = np.sum(dataset, axis=1)
row_sums

array([378, 427, 476, 525, 574, 623, 672])

In [36]:
# Get the sum of the columns in the dataset
column_sums = np.sum(dataset, axis=0)   
column_sums

array([504, 511, 518, 525, 532, 539, 546])

In [37]:
# Get the total sum of the dataset without using np.sum()
total_sum = 0
for i in range(dataset.shape[0]):
    for j in range(dataset.shape[1]):
        total_sum += dataset[i, j]
total_sum

np.int64(3675)

In [40]:
# Get the row sum without using np.sum()
cols = len(dataset[0])
rows = len(dataset)

for r in range(rows):
    row_sum = 0
    for c in range(cols):
        row_sum += dataset[r, c]
    print(f"Sum of row {r}: {row_sum}")

Sum of row 0: 378
Sum of row 1: 427
Sum of row 2: 476
Sum of row 3: 525
Sum of row 4: 574
Sum of row 5: 623
Sum of row 6: 672


In [41]:
# Get the column sum without using np.sum()
cols = len(dataset[0])
rows = len(dataset)

for c in range(cols):
    column_sum = 0
    for r in range(rows):
        column_sum += dataset[r, c]
    print(f"Sum of column {c}: {column_sum}")


Sum of column 0: 504
Sum of column 1: 511
Sum of column 2: 518
Sum of column 3: 525
Sum of column 4: 532
Sum of column 5: 539
Sum of column 6: 546


In [42]:
# First we need to create a matrix with numbers between  to 50
matrix = np.random.randint(0,51,(10,10))
matrix

# Then we need to add -100 to some 10 random places in the matrix
for i in range(10):
    row = np.random.randint(0,10)
    col = np.random.randint(0,10)
    matrix[row][col] = -100
matrix

array([[  31,   34,    8,    2,    1,   12,   34,   39,   28,   50],
       [  27,   28, -100,   47,   46,   28,   29,    8,    2, -100],
       [   6,    4,    9,   50,   43,   30,   15,   38,   40,   42],
       [  11,   43,   48,    5,   34,    4,   36, -100, -100,   12],
       [  13,   21,   21,   35,   40, -100,   22,   22, -100,   17],
       [  27, -100,    4,   29,   15,   18,   41,   49,   37, -100],
       [  17,   36,   17,   27,   19,   32,   37,   13,    2,   46],
       [  24,   34,    9,   26,   29,   19,    3,   14, -100,   38],
       [-100,   45,   28,   23,   20,    6,    2,    5,   38,   29],
       [   9,   49,   44,   28,   16,   25,   22,   40,   26,    2]],
      dtype=int32)

In [43]:
masked_matrix = np.ma.masked_equal(matrix, -100)
masked_matrix

# We replaced thosed masked values of the matrix with 0
clean_matrix = masked_matrix.filled(0)
clean_matrix

array([[31, 34,  8,  2,  1, 12, 34, 39, 28, 50],
       [27, 28,  0, 47, 46, 28, 29,  8,  2,  0],
       [ 6,  4,  9, 50, 43, 30, 15, 38, 40, 42],
       [11, 43, 48,  5, 34,  4, 36,  0,  0, 12],
       [13, 21, 21, 35, 40,  0, 22, 22,  0, 17],
       [27,  0,  4, 29, 15, 18, 41, 49, 37,  0],
       [17, 36, 17, 27, 19, 32, 37, 13,  2, 46],
       [24, 34,  9, 26, 29, 19,  3, 14,  0, 38],
       [ 0, 45, 28, 23, 20,  6,  2,  5, 38, 29],
       [ 9, 49, 44, 28, 16, 25, 22, 40, 26,  2]], dtype=int32)

In [47]:
# Create random dataset with the manufacturing year of 10 cars between 2010 and 2020
manufacturing_years = np.random.randint(2010, 2021, 10)

# Selling price of the 10 cars between 2000€ to 6000€
selling_prices = np.random.randint(2000, 6001, 10)

# First we need to find the indexes that would sort the manufacture year
sorted_indexes = np.argsort(manufacturing_years)

# Then we need to sort the selling prices according to the sorted indexes of the manufacture year
sorted_selling_prices = selling_prices[sorted_indexes]

# Finally we need to sort the manufacture year
sorted_manufacturing_years = manufacturing_years[sorted_indexes]

print("Sorted Manufacturing Years:", sorted_manufacturing_years)
print("Sorted Selling Prices:", sorted_selling_prices)

Sorted Manufacturing Years: [2010 2010 2011 2012 2012 2014 2015 2016 2018 2020]
Sorted Selling Prices: [3493 3099 4435 3931 4935 3966 4294 4535 2385 2120]


In [48]:
# We use repeat() to expand the dataset, when we are using in machine learning
dataset = np.array([1, 2, 3])
expanded_dataset = np.repeat(dataset, 3)    
expanded_dataset

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [49]:
# When we need to convert a matrix in to 1D array we can use ravel() method
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_matrix = matrix.ravel()
flattened_matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# When we need to split the dataset into parts - we use hsplit() and vsplit() functions
data_set = np.array([[1,2,3,4],[5,6,7,8]])
horizontal_split = np.hsplit(data_set,2)
print(f'Horizontal Split: {horizontal_split}')

vertical_split = np.vsplit(data_set,2)
print(f'Vertical Split: {vertical_split}')

Horizontal Split: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Vertical Split: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [56]:
# When wen use to merge the dataset together we can use hstack() and vstack() functions
# Create two datasets to merge
dataset1 = np.array([[1, 2], [3, 4]])
dataset2 = np.array([[5, 6], [7, 8]])

# Merge the datasets horizontally
merged_horizontal = np.hstack((dataset1, dataset2))
print(f'Merged Horizontally:\n{merged_horizontal}')

# Merge the datasets vertically
merged_vertical = np.vstack((dataset1, dataset2))   
print(f'Merged Vertically:\n{merged_vertical}')

Merged Horizontally:
[[1 2 5 6]
 [3 4 7 8]]
Merged Vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [60]:
# We use np.transpose() to transpose the dataset - rows become columns and columns become rows
dataset = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
transposed_dataset = np.transpose(dataset)
transposed_dataset

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [58]:
# When we want to categorize the numerical data into bins we can use np.digitize() function
data = np.array([1, 5, 10, 15, 20])
bins = [0, 5, 10, 15, 20]
categories = np.digitize(data, bins)    
categories

array([1, 2, 3, 4, 5])

In [61]:
# if we want to add additional shape to the dataset we can use np.expand_dims() function
dataset = np.array([1, 2, 3, 4, 5])
expanded_dataset = np.expand_dims(dataset, axis=0)
expanded_dataset

array([[1, 2, 3, 4, 5]])

In [62]:
# If we want to remove the additional shape we can use np.squeeze() function
squeezed_dataset = np.squeeze(expanded_dataset) 
squeezed_dataset

array([1, 2, 3, 4, 5])